version: 2
jobs:
  # build job omitted for brevity
  #deploy:
  build:
    working_directory: ~/working
    
    docker:
      - image: circleci/python:2.7-jessie
      - image: circleci/node:10.8.0
    
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/workspace/node_modules
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
 
      # XXX: npm install is needed(?)
      - run: 
          name: Compile react project
          command: npm --prefix ./frontend build 
      - run:
          name: Deploy to S3
          command: aws s3 sync ./frontend/build s3://booking-dapp.s3-website-ap-northeast-1.amazonaws.com --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master